### ISSUE TITLE
wierd problem with the empty method

### ISSUE THREAD

**Issue by webfactorybulgaria** [TypiCMS/History#5]
Hi, 
We have a weird problem with the empty method in History/src/Repositories/EloquentHistory.php. A simple code like this:
class test
{
    public function empty()
    {
        return 1;
    }
}
results in 
"Parse error: syntax error, unexpected 'empty' (T_EMPTY), expecting identifier (T_STRING) in  ..."
I tested this on a couple of servers with PHP 5.6 and PHP 5.3. PHP 7 doesn't seem to have problem with this. I guess "empty" is a reserved word. Maybe you could use the name "clear" instead...

**Comment by sdebacker** [comment]
This issue is fixed.
